package com.fuchuan.unuseful_mis.model;

import com.fuchuan.unuseful_mis.model.base.BaseClazz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Clazz extends BaseClazz<Clazz> {
	public static final Clazz dao = new Clazz().dao();
}
