package com.fuchuan.unuseful_mis.model;

import com.fuchuan.unuseful_mis.model.base.BaseScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Score extends BaseScore<Score> {
	public static final Score dao = new Score().dao();
}
