package com.fuchuan.unuseful_mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCreditHour(java.lang.Double creditHour) {
		set("creditHour", creditHour);
	}
	
	public java.lang.Double getCreditHour() {
		return getDouble("creditHour");
	}

	public void setCourseHour(java.lang.Double courseHour) {
		set("courseHour", courseHour);
	}
	
	public java.lang.Double getCourseHour() {
		return getDouble("courseHour");
	}

	public void setPriorCourse(java.lang.Long priorCourse) {
		set("priorCourse", priorCourse);
	}
	
	public java.lang.Long getPriorCourse() {
		return getLong("priorCourse");
	}

}
