package com.fuchuan.unuseful_mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClazz<M extends BaseClazz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setInstitute(java.lang.String institute) {
		set("institute", institute);
	}
	
	public java.lang.String getInstitute() {
		return getStr("institute");
	}

	public void setGrade(java.lang.String grade) {
		set("grade", grade);
	}
	
	public java.lang.String getGrade() {
		return getStr("grade");
	}

	public void setNum(java.lang.Long num) {
		set("num", num);
	}
	
	public java.lang.Long getNum() {
		return getLong("num");
	}

}
