package com.fuchuan.unuseful_mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScore<M extends BaseScore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCourseId(java.lang.Long courseId) {
		set("courseId", courseId);
	}
	
	public java.lang.Long getCourseId() {
		return getLong("courseId");
	}

	public void setStudentId(java.lang.Long studentId) {
		set("studentId", studentId);
	}
	
	public java.lang.Long getStudentId() {
		return getLong("studentId");
	}

	public void setTerm(java.lang.String term) {
		set("term", term);
	}
	
	public java.lang.String getTerm() {
		return getStr("term");
	}

	public void setScore(java.lang.Double score) {
		set("score", score);
	}
	
	public java.lang.Double getScore() {
		return getDouble("score");
	}

}
